name: Watch

on:
  workflow_dispatch:
  schedule:
    - cron: '30 */4 * * *'

jobs:
  docker:
    name: Push tagged docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Update Dockerfile with latest version
        id: fetch_version
        run: |
          last=$(curl -s https://packagist.org/packages/vimeo/psalm.json|jq '[.package.versions[]|select(.version|test("^\\d+\\.\\d+\\.\\d+$"))|.version]|max_by(.|[splits("[.]")]|map(tonumber))')
          last=$(echo $last | tr -d '"')
          echo "Last Psalm version is $last"
          echo "last=$last" >> $GITHUB_OUTPUT

          sed -i -re "s/require vimeo\/psalm/require vimeo\/psalm:$last/" Dockerfile
          cat Dockerfile
      - name: Docker login
        uses:  docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build images
        run: docker build -t vimeo/psalm-github-actions:${{ steps.fetch_version.outputs.last }} .

      - name: Publish
        run: docker push vimeo/psalm-github-actions:${{ steps.fetch_version.outputs.last }}
